baseURL: "https://eddy.lu"
languageCode: en-us
title: ed
theme: PaperMod

params:
  homeInfoParams:
    Title: '🏄‍♂️ eddy 的博客'
    Content: '记录一些探索，然后觉得做一个网站比较屌而已'


outputs:
  home:
    - HTML
    - RSS
    - JSON 


menu:
  main:
    - identifier: 分类
      name: 分类
      url: /categories/
      weight: 20
    - identifier: 标签
      name: 标签
      url: /tags/
      weight: 20
    - identifier: 关于我
      name: 关于我
      url: /about/
      weight: 20
    - identifier: 文章列表
      name: 文章列表
      url: /archives/
      weight: 20
    - identifier: 搜索
      name: 搜索
      url: /search/
      weight: 35
    - identifier: 文章
      name: 文章
      url: /posts/
      weight: 9
    - identifier: 近况
      name: 近况
      url: /now/
      weight: 30
    - identifier: 1
      name: 
      url: /1/
      weight: 50
    - identifier: 2
      name: 
      url: /2/
      weight: 50
    - identifier: 3
      name: 
      url: /3/
      weight: 50
    - identifier: 4
      name: 
      url: /4/
      weight: 50
      

